[package]
name = "flood-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "flood_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }
tdlib.workspace = true

[dependencies]
flood-core = { path = "../crates/flood-core" }
notify = "8.2.0"
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.5", features = [] }
tauri-plugin-opener = "2.5.4"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.11.0"
tdlib.workspace = true
tokio.workspace = true
ulid.workspace = true
